name: courier_app
description: Courier Delivery App - Medicine Exchange Platform

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter

  # Shared package - REMOVED to use HTTP-based auth service

  # Firebase (Updated versions for better web compatibility)
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  firebase_messaging: ^15.1.3
  cloud_functions: ^5.1.3

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # UI Components
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9

  # Maps & Location (Courier specific)
  google_maps_flutter: ^2.5.0
  location: ^5.0.3
  geolocator: ^10.1.0

  # QR Scanning (Courier specific) 
  mobile_scanner: ^3.5.6
  
  # Camera (Courier specific)
  camera: ^0.10.5+5
  path_provider: ^2.1.1
  path: ^1.8.0

  # Utilities  
  intl: ^0.18.1
  cached_network_image: ^3.3.0
  qr_flutter: ^4.1.0
  url_launcher: ^6.2.1

  # Local Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0

  # Network
  connectivity_plus: ^5.0.1
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/