// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcsUpbSHE4RHy8JKA3nm-91KKeju8B5Ko',
    appId: '1:850077575356:web:67c7130629f17dd57708b9',
    messagingSenderId: '850077575356',
    projectId: 'mediexchange',
    authDomain: 'mediexchange.firebaseapp.com',
    storageBucket: 'mediexchange.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9ByaBJZtkKh1PO6-FLwH3CK-Jmo2Om0Q',
    appId: '1:850077575356:android:e646509048959fbc7708b9',
    messagingSenderId: '850077575356',
    projectId: 'mediexchange',
    storageBucket: 'mediexchange.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo7SJPapOF0kZwO-L4a4dksqivZyB-Ivw',
    appId: '1:850077575356:ios:c6dac3a4bebb51317708b9',
    messagingSenderId: '850077575356',
    projectId: 'mediexchange',
    storageBucket: 'mediexchange.firebasestorage.app',
    iosBundleId: 'com.pharmapp.pharmacy',
  );
}
